# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24235d0a2c377f95cbe11b03d94f5816ec2a80f2f6413e2f8941eea4507049d1c4adfb5a2334d095d61bc00d7c75b1a06c1703c67ffecd234d6f49cc26d453b1

test:
  secret_key_base: 80b705de28f0d7d5aa87df89550e928717d72e541d64bacfebc075405a6288c2e81d6c254d2b0eb5803fdba8dc3d41d8633f38cccb7b40e7818e593e364fef9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
